# -*- coding: utf-8 -*-
"""Problem-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)

trials = 1000
hits = 0

hit_x = []
hit_y = []

miss_x = []
miss_y = []

for i in range(trials):
    D = np.random.uniform(low=0, high=5/2)
    theta = np.random.uniform(low=0, high=np.pi)

    # hit condition
    if D <= (5/2)*np.sin(theta):
        hits += 1
        hit_x.append(theta)
        hit_y.append(D)
    else:
        miss_x.append(theta)
        miss_y.append(D)

# print(hits)
est_pi = (2*trials/hits)
print(est_pi)
print(np.pi)

plt.scatter(hit_x, hit_y, c='red')
plt.scatter(miss_x, miss_y, c='green')


figure, axes = plt.subplots()

x = np.linspace (-8 , 8)
y = np.linspace (-6 , 6)

a , b = np.meshgrid ( x , y )
Z = (a-3)**2 + (b-1)**2 - 5**2

axes.contour( a , b , Z , [0] , colors='red' )
axes.set_aspect( 1 )

plt.show()