# -*- coding: utf-8 -*-
"""Problem-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

n = int(input("Input any number: "))
s = input("Input the Sentence: ")

arr = []
arr = s.split()
z=[]

if n == len(arr):
    max_len = -1
    for i in arr:
        if len(i) > max_len:
            max_len = len(i)
            max_str = i

    for k in arr:
        z.append(max_len - len(k))

    for row in range(0,n+2):
        for col in range(0,max_len+2):
                           
            if(row==0 or row==(n+2)-1 or col==0 or col==(max_len+2)-1):
                print("*", end="")
      
            elif col==1:
                print(arr[row-1], end= "")
              
                for j, value in enumerate(z):
                    if j==0:
                        print(z[0]*' ', end='') 
                        z.pop(0)            
                                        
        print("\n")
        

elif n > len(arr) or n < len(arr):
    print ("Word count mismatch. Try again!")


# print(max_len)
# print(z)