# -*- coding: utf-8 -*-
"""Problem-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

n = int(input("Input any number: "))

sum = 0
     
while(n > 0 or sum > 9):
     
    if(n == 0):
        n = sum
        sum = 0
         
    sum += n % 10
    n //= 10

    
print (sum)