# -*- coding: utf-8 -*-
"""online3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u57nQG78vDQSlkF5RHuw7MQLBCE4X-Q8
"""

p=1
q=7
r=1
w=0
x=7
y=1

z_1 = [q,7,5]

z_2 = [r,4]

first_one =(2 * z_1[0] + 7 * z_2[0]) % 17 
second_one =(2 * z_1[1] + 7 * z_2[1]) % 17 

z_numbers = [first_one, second_one]
final_numbers = []

for i in range(3,20): 
    z_1.append((3 * (z_1[i-1])**2 + p * z_1[i-2] + w * z_1[i-3]) % 15)
    
for i in range(2,20):
    z_2.append( (8 * (z_2[i-1])**3 + x * z_2[i-2] + y) % 17)

    # z_numbers.append( (2 * z_1[i] + 7 * z_2[i]) % 17 )

for i in range(2,20):
    z_numbers.append( (2 * z_1[i] + 7 * z_2[i]) % 17 )

for i in range(0,20):
    final_numbers.append(z_numbers[i] / 17)


# print(len(z_1))
# print(len(z_2))
# print(len(z_numbers))
# print(z_1)
# print(z_numbers)
print(final_numbers)