# -*- coding: utf-8 -*-
"""Problem-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)

trials = 10000
hits = 0
r=2

hit_x = []
hit_y = []

miss_x = []
miss_y = []

for i in range(trials):
    x = np.random.uniform(low=2, high=8)
    y = np.random.uniform(low=0, high=6)

    # hit condition
    if x>=2 and x<=6:
        #check rectangle
        if y<=4:
            hits += 1
            hit_x.append(x)
            hit_y.append(y)
        elif y>=4:
        #check circle
            if (x-4)**2 + (y-4)**2 <= r**2:
                hits += 1
                hit_x.append(x)
                hit_y.append(y)
            else:
                miss_x.append(x)
                miss_y.append(y)
    else:
        # check triangle
        if x>=6:
              if y < 2 :
                  if y >= x-6:
                    hits += 1
                    hit_x.append(x)
                    hit_y.append(y)
                  else:
                    miss_x.append(x)
                    miss_y.append(y)
              elif y>2:
                  if y-4 <= -x+6:
                    hits += 1
                    hit_x.append(x)
                    hit_y.append(y)
                  else:
                    miss_x.append(x)
                    miss_y.append(y)     
area = (hits/trials)*(6*6)
print(area)

plt.scatter(hit_x, hit_y, c='red')
plt.scatter(miss_x, miss_y, c='green')