# -*- coding: utf-8 -*-
"""Problem-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

import numpy as np
np.random.seed(1)

trials = 1000
hits = 0
f_sum = 0
f_sq_sum=0

for i in range(trials):
    x = np.random.uniform(low=-1, high=2)
    y= (3*x**2 + 2*x)*np.exp(x)
    f_sum += y
    f_sq_sum+=y**2

f_avg = f_sum/trials
f_sq_avg = f_sq_sum/trials
I = f_avg*(2+1)
error= (2+1)/np.sqrt(trials) * np.sqrt(f_sq_avg - f_avg**2)

# Integral    
print(I)
print(error)