# -*- coding: utf-8 -*-
"""online.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NYMDTAhzSUfQtYOWQrfLs5paP3WKwO3B
"""

my_list = [5,	10,	5,	30,	25,	10,	10]
a=[]
b=[]
c=[]

num_of_rounds = int(input("Input any number: "))

for i in range(num_of_rounds):
    index_1 = int(input("Input 1st number: "))
    index_2 = int(input("Input 2nd number: "))
   
    for j, value in enumerate(my_list):
        if index_1==j:
            if index_2==j:
                a.append(index_1)
                b.append(index_2)
                c.append(my_list[index_1])
                my_list.insert(index_2, my_list[index_1])
                my_list.insert(index_1, c)

    # print(my_list)
    # print(c)
            print(a)
            print(b)


        # else:
        #   print("Try again!")

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)

trials = 1000
hits = 0

hit_x = []
hit_y = []

miss_x = []
miss_y = []

for i in range(trials):
    x = np.random.uniform(low=-2, high=5)
    y = np.random.uniform(low=1, high=7)

    Z = (x-2)**2 + (y-4)**2 - 2**2
    # Z= sqrt(2**2 - (x-2)**2)
    # hit condition
    if Z <= 2:
        hits += 1
        hit_x.append(x)
        hit_y.append(y)
    else:
        miss_x.append(x)
        miss_y.append(y)

# print(hits)
est_pi = ((7*6*hits)/(2**2*trials))*2
print(est_pi)
# print(np.pi)

plt.scatter(hit_x, hit_y, c='red')
plt.scatter(miss_x, miss_y, c='green')