# -*- coding: utf-8 -*-
"""offline-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6Z4jC2LHCrvYyiBM1o4-FgxJFVNOqIx
"""

#offline 3 Sharmin 011171071

Z_1 = [171071]
U_1 = [] #R.N.
array_len = 64

for i in range(0,array_len+16):
  z = Z_1[-1]
  z_sq = z**2
  suffix = z_sq % 1000000000  #last 9 digit 
  prefix = int(suffix/1000) #mid 6 digit 

  # if prefix in Z:
  #   break

  u = prefix/1000000  
  U_1.append(u)
  Z_1.append(prefix)
 

print('generated random numbers:', U_1)
print('......................')

Z_2 = [3,7,6]

index = []
m = 17

U_2 = [3/m, 7/m, 6/m] #R.N.

for i in range(3,16):
  Z_2.append((3 * Z_2[i-1] + Z_2[i-2] + 7 * Z_2[i-3]) % m)
  U_2.append(Z_2[i]/m)


for i in range(0,16): 
    x = int(U_2[i]*array_len)
    index.append(x)
    add_value = U_1[array_len+i]
    U_1.pop(index[i])
    U_1.insert(index[i], add_value)

    # print(U_1)
   
print('modified random numbers:',U_1)

print('......................')
print("changed index positions:", index)



